Use [InfiniteInfluence]
-- DATA GENERATED BY MICROSOFT COPILOT, MANUALLY EDITED TO BE MORE USEFUL. LINKS ARE BROKEN.

BEGIN TRANSACTION
-- Sample Influencers.
INSERT INTO [Influencer] 
    ([Username], [Credentials], [DisplayName], [VerificationStatus], [ProfileImageUrl], [Location], [MainPlatformUrl], [Followers])
VALUES
('trendsetter01', 'password123', 'Trend Setter', 1, 'https://images.com/trendsetter01.jpg', 'New York, USA', 'https://instagram.com/trendsetter01', 120000),
('foodiequeen', 'ilovecooking!', 'Foodie Queen', 1, 'https://images.com/foodiequeen.jpg', 'Los Angeles, USA', 'https://youtube.com/foodiequeen', 85000),
('techguru', 'securePass!', 'Tech Guru', 1, 'https://images.com/techguru.jpg', 'San Francisco, USA', 'https://twitter.com/techguru', 200000),
('travelbug', 'wanderlust2025', 'Travel Bug', 0, 'https://images.com/travelbug.jpg', 'London, UK', 'https://instagram.com/travelbug', 95000),
('fitnessfreak', 'strongPass!', 'Fitness Freak', 1, 'https://images.com/fitnessfreak.jpg', 'Berlin, Germany', 'https://tiktok.com/@fitnessfreak', 300000),
('artlover', 'paintBrush!', 'Art Lover', 0, 'https://images.com/artlover.jpg', 'Paris, France', 'https://instagram.com/artlover', 45000),
('gamemaster', 'gameOn!', 'Game Master', 1, 'https://images.com/gamemaster.jpg', 'Tokyo, Japan', 'https://twitch.tv/gamemaster', 500000),
('styleicon', 'fashionPass!', 'Style Icon', 1, 'https://images.com/styleicon.jpg', 'Milan, Italy', 'https://instagram.com/styleicon', 220000),
('bookworm', 'readMore!', 'Book Worm', 0, 'https://images.com/bookworm.jpg', 'Toronto, Canada', 'https://youtube.com/bookworm', 60000),
('musicmaniac', 'melodyPass!', 'Music Maniac', 1, 'https://images.com/musicmaniac.jpg', 'Nashville, USA', 'https://spotify.com/musicmaniac', 180000),
('ecohero', 'greenPass!', 'Eco Hero', 1, 'https://images.com/ecohero.jpg', 'Copenhagen, Denmark', 'https://instagram.com/ecohero', 75000),
('chefmaster', 'cookPass!', 'Chef Master', 1, 'https://images.com/chefmaster.jpg', 'Barcelona, Spain', 'https://youtube.com/chefmaster', 130000),
('dancequeen', 'dancePass!', 'Dance Queen', 0, 'https://images.com/dancequeen.jpg', 'Mumbai, India', 'https://tiktok.com/@dancequeen', 400000),
('sciencegeek', 'labPass!', 'Science Geek', 1, 'https://images.com/sciencegeek.jpg', 'Boston, USA', 'https://twitter.com/sciencegeek', 95000),
('petlover', 'petsPass!', 'Pet Lover', 1, 'https://images.com/petlover.jpg', 'Sydney, Australia', 'https://instagram.com/petlover', 120000),
('historybuff', 'historyPass!', 'History Buff', 0, 'https://images.com/historybuff.jpg', 'Athens, Greece', 'https://youtube.com/historybuff', 40000),
('startupguru', 'bizPass!', 'Startup Guru', 1, 'https://images.com/startupguru.jpg', 'Tel Aviv, Israel', 'https://linkedin.com/in/startupguru', 150000),
('momblogger', 'familyPass!', 'Mom Blogger', 0, 'https://images.com/momblogger.jpg', 'Chicago, USA', 'https://instagram.com/momblogger', 300),
('photogenius', 'photoPass!', 'Photo Genius', 1, 'https://images.com/photogenius.jpg', 'Amsterdam, Netherlands', 'https://flickr.com/photogenius', 80000);

-- Sample Companies
INSERT INTO [Company] 
    ([Username], [Credentials], [CompanyName], [VerificationStatus], [CompanyLogoUrl], [Location], [Email], [PhoneNumer])
VALUES
('techworld', 'securePass123', 'Tech World Inc.', 1, 'https://logos.com/techworld.png', 'San Francisco, USA', 'contact@techworld.com', '+1-415-555-1001'),
('greenenergy', 'ecoPass456', 'Green Energy Solutions', 1, 'https://logos.com/greenenergy.png', 'Berlin, Germany', 'info@greenenergy.de', '+49-30-555-2002'),
('fashionhub', 'stylePass789', 'Fashion Hub Ltd.', 0, 'https://logos.com/fashionhub.png', 'Milan, Italy', 'support@fashionhub.it', '+39-02-555-3003'),
('medicare', 'healthPass321', 'Medicare Group', 1, 'https://logos.com/medicare.png', 'London, UK', 'hello@medicare.co.uk', '+44-20-555-4004'),
('travelmate', 'wanderPass654', 'Travel Mate Co.', 0, 'https://logos.com/travelmate.png', 'Sydney, Australia', 'contact@travelmate.com.au', '+61-2-555-5005'),
('foodiespot', 'tastePass987', 'Foodie Spot', 1, 'https://logos.com/foodiespot.png', 'New York, USA', 'info@foodiespot.com', '+1-212-555-6006'),
('gameverse', 'playPass111', 'GameVerse Studios', 1, 'https://logos.com/gameverse.png', 'Tokyo, Japan', 'support@gameverse.jp', '+81-3-555-7007'),
('artvision', 'paintPass222', 'Art Vision', 0, 'https://logos.com/artvision.png', 'Paris, France', 'contact@artvision.fr', '+33-1-555-8008'),
('finserve', 'moneyPass333', 'FinServe Bank', 1, 'https://logos.com/finserve.png', 'Toronto, Canada', 'info@finserve.ca', '+1-416-555-9009');

-- Sample announcements
INSERT INTO [Announcement] 
    ([BannerUrl], [Title], [Description], [StatusType], [VisibilityState], [MaximumApplicants], [RequiredFollowers], [CompanyId])
VALUES
('https://banners.com/techworld_launch.jpg', 'Product Launch', 'Tech World is launching its new AI-powered product line this December.', 1, 1, 500, 10000, 1),
('https://banners.com/greenenergy_event.jpg', 'Sustainability Summit', 'Green Energy Solutions invites you to join our annual sustainability summit.', 1, 1, 300, 5000, 2),
('https://banners.com/fashionhub_sale.jpg', 'Winter Sale', 'Fashion Hub announces its exclusive winter collection sale with up to 50% off.', 1, 1, 1000, 2000, 3),
('https://banners.com/medicare_hiring.jpg', 'We Are Hiring', 'Medicare Group is hiring healthcare professionals across multiple departments.', 1, 1, 200, 0, 4),
('https://banners.com/travelmate_offer.jpg', 'Holiday Offer', 'Travel Mate Co. offers discounted packages for the holiday season.', 1, 1, 100, 1000, 5),
('https://banners.com/foodiespot_event.jpg', 'Cooking Contest', 'Foodie Spot is hosting a cooking contest with celebrity chefs.', 1, 1, 50, 500, 6),
('https://banners.com/gameverse_tournament.jpg', 'Gaming Tournament', 'GameVerse Studios announces its annual eSports tournament.', 1, 1, 500, 20000, 7),
('https://banners.com/artvision_exhibit.jpg', 'Art Exhibit', 'Art Vision presents a new exhibit featuring modern artists.', 1, 1, 150, 1000, 8),
('https://banners.com/finserve_investment.jpg', 'Investment Opportunity', 'FinServe Bank introduces new investment opportunities for clients.', 1, 1, 100, 5000, 9),
('https://banners.com/buildit_project.jpg', 'Mega Project', 'BuildIt Corp. announces a new mega construction project in Chicago.', 1, 1, 300, 0, 1),
('https://banners.com/ecoshop_campaign.jpg', 'Eco Campaign', 'EcoShop Market launches a campaign to reduce plastic usage.', 1, 1, 200, 1000, 2),
('https://banners.com/startupx_pitch.jpg', 'Pitch Event', 'StartupX invites entrepreneurs to pitch their ideas.', 1, 1, 100, 500, 3),
('https://banners.com/momcare_workshop.jpg', 'Parenting Workshop', 'MomCare Services hosts a free parenting workshop.', 1, 1, 50, 0, 4),
('https://banners.com/photopro_contest.jpg', 'Photo Contest', 'PhotoPro Agency announces a global photography contest.', 1, 1, 200, 1000, 5),
('https://banners.com/codeworks_hackathon.jpg', 'Hackathon', 'CodeWorks Ltd. is organizing a hackathon for developers.', 1, 1, 300, 2000, 6),
('https://banners.com/techworld_update.jpg', 'System Update', 'Tech World releases a major update to its platform.', 1, 1, 2, 0, 7),
('https://banners.com/greenenergy_award.jpg', 'Award Ceremony', 'Green Energy Solutions wins the Global Sustainability Award.', 1, 1, 5, 10, 8),
('https://banners.com/fashionhub_show.jpg', 'Fashion Show', 'Fashion Hub presents its spring collection in Milan.', 1, 1, 500, 5000, 9),
('https://banners.com/medicare_campaign.jpg', 'Health Campaign', 'Medicare Group launches a nationwide health awareness campaign.', 1, 1, 30, 0, 1),
('https://banners.com/travelmate_tour.jpg', 'Exclusive Tour', 'Travel Mate Co. offers an exclusive guided tour to Bali.', 1, 1, 100, 2000, 2),
('https://banners.com/gameverse_beta.jpg', 'Beta Release', 'GameVerse Studios announces beta testing for its new game.', 1, 1, 200, 5000, 3);
GO

-- Sample Applications
INSERT INTO [AnnouncementInfluencer] 
    ([AnnouncementId], [InfluencerId], [ApplicationDate])
VALUES
(1, 1, '2025-11-01T10:15:00'),
(1, 2, '2025-11-01T11:00:00'),
(2, 3, '2025-11-02T09:30:00'),
(2, 4, '2025-11-02T10:45:00'),
(3, 5, '2025-11-03T14:20:00'),
(3, 6, '2025-11-03T15:10:00'),
(4, 7, '2025-11-04T08:00:00'),
(4, 8, '2025-11-04T09:15:00'),
(5, 9, '2025-11-05T13:00:00'),
(5, 10, '2025-11-05T14:30:00'),
(6, 11, '2025-11-06T16:45:00'),
(6, 12, '2025-11-06T17:20:00'),
(7, 13, '2025-11-07T12:00:00'),
(7, 14, '2025-11-07T12:45:00'),
(8, 15, '2025-11-08T09:00:00'),
(8, 16, '2025-11-08T10:30:00'),
(9, 17, '2025-11-09T11:15:00'),
(14, 18, '2025-11-09T12:40:00'),
(10, 19, '2025-11-10T15:00:00'),
(10, 1, '2025-11-10T16:10:00'),
(11, 2, '2025-11-11T09:25:00'),
(11, 3, '2025-11-11T10:50:00'),
(12, 4, '2025-11-12T13:15:00'),
(12, 5, '2025-11-12T14:40:00'),
(13, 6, '2025-11-13T08:05:00'),
(13, 7, '2025-11-13T09:30:00'),
(14, 8, '2025-11-14T11:45:00'),
(15, 1, '2025-11-01T09:15:00'),
(15, 2, '2025-11-01T10:30:00'),
(15, 3, '2025-11-01T11:45:00'),
(16, 4, '2025-11-02T09:00:00'),
(16, 5, '2025-11-02T10:20:00'),
(18, 6, '2025-11-02T11:40:00'),
(17, 7, '2025-11-03T13:00:00'),
(17, 8, '2025-11-03T14:15:00'),
(17, 9, '2025-11-03T15:30:00'),
(11, 10, '2025-11-04T09:10:00'),
(12, 12, '2025-11-04T11:40:00'),
(13, 13, '2025-11-05T12:00:00'),
(15, 14, '2025-11-05T13:15:00'),
(14, 15, '2025-11-05T14:30:00'),
(4, 16, '2025-11-06T09:45:00'),
(4, 17, '2025-11-06T11:00:00'),
(3, 18, '2025-11-06T12:15:00'),
(14, 19, '2025-11-07T13:30:00'),
(14, 1, '2025-11-07T14:45:00'),
(15, 4, '2025-11-08T09:00:00'),
(18, 7, '2025-11-08T10:20:00'),
(19, 10, '2025-11-09T11:40:00'),
(18, 13, '2025-11-09T13:00:00'),
(6, 16, '2025-11-10T14:20:00'),
(6, 2, '2025-11-10T15:40:00'),
(21, 5, '2025-11-11T09:10:00'),
(15, 8, '2025-11-11T10:30:00'),
(18, 11, '2025-11-12T11:50:00');

COMMIT;